[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10

[[cron]]
schedule = "0 * * * *"  # Every hour
command = "node scripts/fetch-weather.js" 